
// Authentication
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';
export const SIGNUP_STATUS = "SIGNUP_STATUS";
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_STATUS = "LOGIN_STATUS"
export const USER_LOADED_SUCCESS = 'USER_LOADED_SUCCESS';
export const USER_LOADED_FAIL = 'USER_LOADED_FAIL';
export const ACTIVATION_SUCCESS = 'ACTIVATION_SUCCESS';
export const ACTIVATION_FAIL = 'ACTIVATION_FAIL';
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING';
export const REMOVE_AUTH_LOADING = 'REMOVE_AUTH_LOADING';
export const AUTHENTICATED_SUCCESS = 'AUTHENTICATED_SUCCESS';
export const AUTHENTICATED_FAIL = 'AUTHENTICATED_FAIL';
export const REFRESH_SUCCESS = 'REFRESH_SUCCESS';
export const REFRESH_FAIL = 'REFRESH_FAIL';
export const LOGOUT = 'LOGOUT';
export const SET_SIGN_STATE = 'SET_SIGN_STATE';

export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';
export const RESET_PASSWORD_CONFIRM_SUCCESS = 'RESET_PASSWORD_CONFIRM_SUCCESS';
export const RESET_PASSWORD_CONFIRM_FAIL = 'RESET_PASSWORD_CONFIRM_FAIL';

// Alerts
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';


// listas de procesos
export const VIEW_NEW_PROCESS = "VIEW_NEW_PROCESS";


// dashboard 
export const VIEW_LOCALSERVER = 'VIEW_LOCALSERVER';
export const LOCAL_SERVER_SUCCESS = 'LOCAL_SERVER_SUCCESS';
export const LOCAL_SERVER_FAIL = 'LOCAL_SERVER_FAIL';
export const LOCAL_SERVER_OFF = 'LOCAL_SERVER_OFF';
export const LOCAL_PF_SUCCESS = 'LOCAL_PF_SUCCESS';
export const LOCAL_PF_FAIL = 'LOCAL_PF_FAIL';
export const VIEW_PROJECT = 'VIEW_PROJECT';
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
export const GET_PROJECTS_FAIL = 'GET_PROJECTS_FAIL';
export const SELECT_PRJ = 'SELECT_PRJ';